#
# Blog Settings
#
title: Michel Bechelani
subtitle: A blog about nothing...
description: A blog about nothing...
author: Michel Bechelani
root: https://bechelani.com
url: https://bechelani.com

subscribe_rss: https://bechelani.com/atom.xml

email_md5: a0661c010257531bea5bdacab8fd5712

# Github repositories
github_user: bechelani
github_repo_url: https://github.com/bechelani/bechelani.com/

# Twitter
twitter_user: bechelani

# LinkedIn
linkedin_user: bechelani

# Google Analytics
google_analytics_tracking_id:

kramdown:
  hard_wrap: false

#
# Jekyll Settings
#
permalink: /archive/:year/:month/:day/:title/
paginate: 20
paginate_path: "page/:num"
category_dir: categories

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

feed:
  path: atom.xml

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed
